### ISSUE TITLE
🎃 Hacktoberfest

### ISSUE THREAD

**Issue by HugoHeneault** [marcglasberg/matrix4_transform#12]
Hi there, 

As every year in october, [Hacktoberfest](https://hacktoberfest.digitalocean.com/) has started! :-)
More details here : https://hacktoberfest.digitalocean.com/resources/maintainers 
Would you add the `hacktoberfest` label to your repo so contributors know they can participate and fix issues/craft PRs?

Thanks a lot.

**Comment by sachingagneja** [comment]
Can i Contribute in it?

**Comment by HugoHeneault** [comment]
Well the `hacktoberfest` label hasn't been added yet. You can contribute and if @marcglasberg add it you'll get your PR counted :-)

**Comment by HugoHeneault** [comment]
@marcglasberg Would you consider adding the `hacktoberfest` label to this repo? Then we can close. Thanks alot!

**Comment by marcglasberg** [comment]
Sorry, I didn't have the time to participate. Interesting event, though!
