### ISSUE TITLE
Child gets distorted..

### ISSUE THREAD

**Issue by Tonku** [marcglasberg/matrix4_transform#6]
Hi 
if I scale horizontally but keep the height constant, the child gets distorted. How to make the child resize automatically rather than scale with the parent?

**Comment by marcglasberg** [comment]
I am not sure I understand your question. Could you please elaborate more?

**Comment by Tonku** [comment]
Hi 
I am trying do an image editor.I used the transform but the child widget gets squished, when I try to scale it with height or width fixed.
What I am trying to achieve is in the image attached.

![Screen Shot 2020-03-12 at 9 01 32 pm](https://user-images.githubusercontent.com/530273/76510222-5c59ec80-64a5-11ea-9d7b-421665a3b73e.png)

**Comment by marcglasberg** [comment]
Ok, the image shows what you want to achieve. And what is the result you're obtaining? And what is the code you're using?

**Comment by Tonku** [comment]
I am good mate , I did figure it out thanks :)
