### ISSUE TITLE
problem with from contractor

### ISSUE THREAD

**Issue by mehdizarepour** [marcglasberg/matrix4_transform#7]
Hi!
I want to transform a widget on `onScaleUpdate` event then I used `Matrix4Transform` like this:

```dart
GestureDetector(
  onScaleStart: (d) {
    dx = d.focalPoint.dx;
    dy = d.focalPoint.dy;
  },
  onScaleUpdate: (d) {
    setState(() {
      matrix = Matrix4Transform()
          .translate(x: d.focalPoint.dx - dx, y: d.focalPoint.dy - dy)
          .scale(d.scale)
          .rotate(d.rotation)
          .matrix4;
    });
  },
  child: Center(
    child: Transform(
      transform: matrix,
      alignment: FractionalOffset.center,
      child: Container(width: 100, height: 100, color: Colors.red),
    ),
  ),
)
```

It works fine, but the problem is, I want to keep last transform on `Matrix4` object and use  it on the next transform, then I've tried using `from` contractor like this:

```dart
onScaleUpdate: (d) {
    setState(() {
      matrix = Matrix4Transform.fom(matrix)
          .translate(x: d.focalPoint.dx - dx, y: d.focalPoint.dy - dy)
          .scale(d.scale)
          .rotate(d.rotation)
          .matrix4;
    });
  },
```
But it does not work how I expected, as you can see it's too sharp:
am I using it wrong? any suggestion?

![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/8446770/94329862-81d6bf80-ffcb-11ea-90d6-cc2c54da6051.gif)

**Comment by mehdizarepour** [comment]
@marcglasberg any solutions?

**Comment by marcglasberg** [comment]
Don't do this. Save the cumulative scale/rotation/translate information yourself, in variables, and then calculate the Matrix4 transform from the original scale 1, rotation 0, and position 0.
