### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by md84419** [marcglasberg/matrix4_transform#8]
The library 'package:matrix4_transform/matrix4_transform.dart' is legacy, and should not be imported into a null safe library.
Try migrating the imported library.

Error: This project cannot run with sound null safety, because one or more project dependencies do not
support null safety:

- package:matrix4_transform

dependencies:
  matrix4_transform: ^1.1.6

**Comment by marcglasberg** [comment]
See version [2.0.0-nullsafety.1]
